### ISSUE TITLE
windows binary wallet?

### ISSUE THREAD

**Issue by AkiAfroo** [momopay/momo#1]
hello,
could you be so kind and build windows binary wallet?

**Comment by momocash** [comment]
Dear Akiafroo

The momocash still in dev period,
the config file is not release
I will release the  window 64 and 32 version  soon
thank you for your Attention

thanks && best regards
alemic

**Comment by momocash** [comment]
dear Akiafroo
the download link:
https://www.momocash.org/download/momo.win32.zip
https://www.momocash.org/download/momo.win64.zip
